In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
print(torch.__version__)

2.5.0+cu121


# Intro to Tensors

## Creating Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python Int
scalar.item()

7

In [ ]:
## Vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
## Matrix

MATRIX = torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([1, 2])

In [ ]:
MATRIX[1]

tensor([3, 4])

In [ ]:
# Tensor

TENSOR = torch.tensor([[[[[[1,2,3],[4,5,6],[7,8,9]]]]]])
TENSOR

tensor([[[[[[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]]]]]])

In [ ]:
TENSOR.shape

torch.Size([1, 1, 1, 1, 3, 3])

In [ ]:
TENSOR.ndim

6

### Random Tensors

In [ ]:
# Create random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3336, 0.3007, 0.1671, 0.9248],
        [0.3170, 0.1169, 0.2790, 0.6136],
        [0.2905, 0.6979, 0.7122, 0.0292]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to a image
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [ ]:
## Create a tensor of all zeros
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Range of Tensors

In [ ]:
# Create a range of range
one_to_ten = torch.arange(start= 0,end=10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Create a range of range
torch.arange(start= 0,end=10,step=2)

tensor([0, 2, 4, 6, 8])

In [ ]:
# Create a range of range
torch.arange(start= 1,end=20,step=3)

tensor([ 1,  4,  7, 10, 13, 16, 19])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Data Types

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,  6.0, 9.0],
                               dtype=None, ## Data type of tensor float32 or float16
                               device=None, # CPU OR GPU
                               requires_grad=True)
float_32_tensor

tensor([3., 6., 9.], requires_grad=True)

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16, grad_fn=<ToCopyBackward0>)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], grad_fn=<MulBackward0>)

### Tensor Operations

In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# multiply by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out Pytorch inbuilt functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [ ]:
# Matrix Multiplication (Dot Product)
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
# Element Wise Multiplication
print(tensor * tensor)

tensor([1, 4, 9])


### Tensor Aggregation

In [ ]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Mean
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Mean
torch.mean(x.type(torch.float32)), x.type((torch.float32)).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Positional Min and Max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Position with min value
x.argmin()

tensor(0)

In [ ]:
# Position with max value
x.argmax()

tensor(9)

### Reshaping, Stacking, Squeezing and unsqueezing tensors

In [ ]:
import torch

In [ ]:
x = torch.arange(1., 10.,)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
# Change the view
# Shares memory with original tensor
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:,0] = 222
z, x

(tensor([[222.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]]),
 tensor([222.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[222.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        [222.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        [222.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        [222.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]])

In [ ]:
x_stacked = torch.stack([x,x], dim=1)
x_stacked

tensor([[222., 222.],
        [  2.,   2.],
        [  3.,   3.],
        [  4.,   4.],
        [  5.,   5.],
        [  6.,   6.],
        [  7.,   7.],
        [  8.,   8.],
        [  9.,   9.]])

### Squeeze and Unsqueeze

In [ ]:
x = torch.zeros(2,1,2,1)
x, x.shape

(tensor([[[[0.],
           [0.]]],
 
 
         [[[0.],
           [0.]]]]),
 torch.Size([2, 1, 2, 1]))

In [ ]:
x.squeeze().shape

torch.Size([2, 2])

In [ ]:
x.unsqueeze(dim=1).shape

torch.Size([2, 1, 1, 2, 1])

In [ ]:
x

tensor([[[[0.],
          [0.]]],


        [[[0.],
          [0.]]]])

In [ ]:
# torch permute rearranges dims in specified order
x_original = torch.rand(size=(224,224, 3))
x_original.shape

torch.Size([224, 224, 3])

In [ ]:
x_permute = x_original.permute(2,0,1)
x_permute.shape

torch.Size([3, 224, 224])

### Reproducible results


In [112]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

In [116]:
torch.manual_seed(RANDOM_SEED)
c= torch.rand(3,4)


torch.manual_seed(RANDOM_SEED)
d = torch.rand(3,4)

print(c == d)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## GPU Access

In [2]:
!nvidia-smi

Thu Oct 31 20:50:40 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P8              10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [1]:
import torch
torch.cuda.is_available()

True

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
torch.cuda.device_count()

1